# Generated by Django 3.0.8 on 2021-09-04 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bodega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=256)),
                ('usuario_creacion', models.CharField(max_length=15)),
                ('usuario_modificacion', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'tp_bodega',
            },
        ),
        migrations.CreateModel(
            name='Bodega_producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=5)),
                ('unidad', models.CharField(max_length=10)),
                ('usuario_creacion', models.CharField(max_length=15)),
                ('usuario_modificacion', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'tp_bodega_producto',
            },
        ),
        migrations.CreateModel(
            name='Categoria_producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=256)),
                ('usuario_creacion', models.CharField(max_length=15)),
                ('usuario_modificacion', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'tp_categoria_producto',
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=256)),
                ('usuario_creacion', models.CharField(max_length=15)),
                ('usuario_modificacion', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'tp_devolucion',
            },
        ),
        migrations.CreateModel(
            name='Egreso_cabecera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=256)),
                ('usuario_creacion', models.CharField(max_length=15)),
                ('usuario_modificacion', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'tp_egreso_cabecera',
            },
        ),
        migrations.CreateModel(
            name='Egreso_detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=50)),
                ('precio', models.CharField(max_length=5)),
                ('usuario_creacion', models.CharField(max_length=15)),
                ('usuario_modificacion', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'tp_egreso_detalle',
            },
        ),
        migrations.CreateModel(
            name='ingreso_cabecera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
                ('usuario_creacion', models.CharField(max_length=15)),
                ('usuario_modificacion', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'tp_ingreso_cabecera',
            },
        ),
        migrations.CreateModel(
            name='ingreso_detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
                ('usuario_creacion', models.CharField(max_length=15)),
                ('usuario_modificacion', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'tp_ingreso_detalle',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('usuario_creacion', models.CharField(max_length=15)),
                ('usuario_modificacion', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'tp_marca',
            },
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('usuario_creacion', models.CharField(max_length=15)),
                ('usuario_modificacion', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'tp_producto',
            },
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.CharField(max_length=3)),
                ('direccion', models.CharField(max_length=250)),
                ('celular', models.CharField(max_length=10)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('usuario_creacion', models.CharField(max_length=15)),
                ('usuario_modificacion', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'tp_proveedor',
            },
        ),
        migrations.CreateModel(
            name='rol_persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50)),
                ('usuario_creacion', models.CharField(max_length=15)),
                ('usuario_modificacion', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'tp_rol_persona',
            },
        ),
        migrations.CreateModel(
            name='unidad_medida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('medida', models.CharField(max_length=100)),
                ('usuario_creacion', models.CharField(max_length=15)),
                ('usuario_modificacion', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'tp_unidad_medida',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.CharField(max_length=3)),
                ('direccion', models.CharField(max_length=250)),
                ('cedula', models.CharField(max_length=10)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('usuario_creacion', models.CharField(max_length=15)),
                ('usuario_modificacion', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.IntegerField(default=1)),
                ('Rol_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_inventario.rol_persona')),
            ],
            options={
                'db_table': 'tp_persona',
            },
        ),
    ]
