# Generated by Django 3.0.8 on 2021-10-15 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='egreso_cabecera',
            table='inv_egreso_cabecera',
        ),
    ]
