# Generated by Django 3.0.8 on 2021-09-18 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriabodega',
            old_name='descripcion',
            new_name='descripcion_catbog',
        ),
    ]
