# Generated by Django 3.0.8 on 2021-10-15 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_inventario', '0002_auto_20211014_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='egreso_cabecera',
            old_name='codigo_documento',
            new_name='codigo_documento_eg',
        ),
        migrations.RenameField(
            model_name='egreso_cabecera',
            old_name='fecha_documento',
            new_name='fecha_documento_eg',
        ),
        migrations.RenameField(
            model_name='egreso_cabecera',
            old_name='total_egreso',
            new_name='total_egreso_eg',
        ),
        migrations.RenameField(
            model_name='egreso_cabecera',
            old_name='usuario_entrega',
            new_name='usuario_entrega_eg',
        ),
        migrations.RenameField(
            model_name='egreso_cabecera',
            old_name='usuario_recibe',
            new_name='usuario_recibe_eg',
        ),
        migrations.RenameField(
            model_name='egreso_detalle',
            old_name='sub_total',
            new_name='sub_total_egreso',
        ),
        migrations.RenameField(
            model_name='ingreso_cabecera',
            old_name='codigo_documento',
            new_name='codigo_documento_cabecera',
        ),
        migrations.RenameField(
            model_name='ingreso_cabecera',
            old_name='fecha_documento',
            new_name='fecha_documento_cabecera',
        ),
        migrations.RenameField(
            model_name='ingreso_cabecera',
            old_name='total_ingreso',
            new_name='total_ingreso_cabecera',
        ),
        migrations.RenameField(
            model_name='ingreso_cabecera',
            old_name='usuario_entrega',
            new_name='usuario_entrega_cabecera',
        ),
        migrations.RenameField(
            model_name='ingreso_cabecera',
            old_name='usuario_recibe',
            new_name='usuario_recibe_cabecera',
        ),
        migrations.RenameField(
            model_name='ingreso_detalle',
            old_name='sub_total',
            new_name='sub_total_ingreso',
        ),
    ]
